# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.08 -1.04  2.02 -3.89 -1.6 ]
 [-0.41  0.15 -0.77  0.05  1.46]
 [-0.1   0.99  0.74  0.41  1.98]]
 
[[-0.43  1.42  0.78  1.28]
 [-0.2  -1.47  0.83 -0.4 ]
 [-0.55 -0.72  0.71 -0.72]
 [ 0.41 -0.78  0.55  1.07]
 [ 0.13 -1.52 -0.06 -0.99]
 [ 1.23 -2.05 -0.02  1.02]
 [ 1.85 -3.13 -0.94  0.2 ]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-3.4200,  1.5500,  0.0100, -1.1000, -1.5800,  2.0900,  1.0900],
        [-3.0500,  1.0400, -3.4500, -0.7500, -2.7600, -0.7300,  2.2100],
        [ 0.6900, -0.2200,  1.2100,  0.3100, -0.4300, -0.3500, -0.5500]],
       dtype=torch.float64)
 
tensor([[-3.4200,  1.5500,  0.0100, -1.1000, -1.5800,  2.0900,  1.0900],
        [-3.0500,  1.0400, -3.4500, -0.7500, -2.7600, -0.7300,  2.2100],
        [ 0.6900, -0.2200,  1.2100,  0.3100, -0.4300, -0.3500, -0.5500]])


/tmp/ipykernel_1479744/4136805860.py:10: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  print(np.round( A@C1  ,2)), print(' ')
