# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [ ]:
widenet.

# Peeking inside the network

In [3]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.4073,  0.5204],
        [-0.0964, -0.2418]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.0418, -0.3672], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.5311,  0.5440],
        [-0.0674,  0.2118]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.1054,  0.1707], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.3982,  0.3475],
        [ 0.0418, -0.6077],
        [-0.3060,  0.3595]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.1862,  0.4392, -0.0569], requires_grad=True))
 


In [4]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [5]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.1573, -0.4116],
        [ 0.5969,  0.0484],
        [-0.5865, -0.6478],
        [ 0.1288,  0.3376]], requires_grad=True)
 
Parameter containing:
tensor([ 0.6964,  0.1314, -0.3912,  0.2377], requires_grad=True)
 
Parameter containing:
tensor([[-0.4025, -0.4031,  0.3681,  0.2943],
        [ 0.2176, -0.1565,  0.1542,  0.1853],
        [-0.3412, -0.3108,  0.2622,  0.3650]], requires_grad=True)
 
Parameter containing:
tensor([ 0.0089, -0.4568, -0.4910], requires_grad=True)
 


In [6]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [7]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [9]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)